services:
    log.subscriber:
        class: MWM\LogBundle\EventListener\LogSubscriber
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_subscriber, connection: default   }
